config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tournaments, only: [:edit, :update]

  resources :seasons, except: [:index, :show]

  resources :tours, except: :index do
    member do
      get :results
    end
  end

  resources :problems, except: [:index, :show]

  resources :scores, only: [:create, :update]

  resources :participations, only: [:create, :update]

  resources :solutions, except: [:index, :show]

  resources :users, only: [:index, :update]

  root to: 'tournaments#show'
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  default_scope -> { order(position: :asc) }

  belongs_to :tour

  has_many :solutions, dependent: :restrict_with_exception

  acts_as_list scope: :tour

  validates :content, :tour, presence: true

  def solutions?
    solutions.size > 0
  end

  def solution_for(participation)
    solutions.find_by(participation: participation)
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  load_and_authorize_resource except: [:index, :new]

  decorates_assigned :problem

  before_action :prepare_breadcrumbs, only: :edit

  helper_method :current_participation

  def new
    @problem = Problem.new(tour_id: params[:tour_id])
    authorize! :new, @problem
    prepare_breadcrumbs
  end

  def edit
  end

  def create
    if @problem.save
      redirect_to @problem.tour, notice: t('model.created')
    else
      render :new
    end
  end

  def update
    if @problem.update(problem_params)
      redirect_to @problem.tour, notice: t('model.updated')
    else
      render :edit
    end
  end

  def destroy
    @problem.destroy

    redirect_to @problem.tour, notice: t('model.destroyed')
  end

  private

  def current_participation
    @current_participation ||= current_user_participations.find_by(
      season: @problem.try(:tour).try(:season)
    ) if @problem.present?
  end

  def problem_params
    params.require(:problem).permit(:tour_id, :content)
  end

  def prepare_breadcrumbs
    add_breadcrumb @problem.tour.season.tournament.name, :root_path
    add_breadcrumb @problem.tour.season.name, :root_path
    add_breadcrumb @problem.tour.name, @problem.tour
    add_breadcrumb @problem.decorate.name, @problem
  end
end

app/views/problems/_form.html.slim
= bootstrap_form_for problem do |f|
  = f.text_area :content, data: { provide: 'markdown' }
  = f.hidden_field :tour_id
  = f.submit

app/views/problems/_problem.html.slim
.problem
  .panel.panel-default
    .panel-heading
      = problem.name

      = actions_for problem, class: 'pull-right'
    .panel-body
      .content
        =m problem.content
        - if solution = problem.solution_for(current_participation)
          - if can? :update, solution
            .well
              = actions_for solution, class: 'pull-right'
              = solution.content
        - elsif can? :create, Solution.new(problem: problem)
          = link_to 'Answer', new_solution_path(participation_id: current_participation.id, problem_id: problem.id)
        - if can? :judge, problem.tour
          = render 'judgement_form', problem: problem

app/views/problems/edit.html.slim
h3
  => t('header.edit')

= render 'form', problem: @problem

app/views/problems/new.html.slim
h3
  => t('header.new')

= render 'form', problem: @problem