config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tournaments, only: [:edit, :update]

  resources :seasons, except: [:index, :show]

  resources :tours, except: :index do
    member do
      get :results
    end
  end

  resources :problems, except: [:index, :show]

  resources :scores, only: [:create, :update]

  resources :participations, only: [:create, :update]

  resources :solutions, except: [:index, :show]

  resources :users, only: [:index, :update]

  root to: 'tournaments#show'
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :season

  has_many :problems, dependent: :destroy

  scope :active, -> { where('tours.started_at <= ?', Time.zone.now) }

  scope :solutionable, lambda {
    where('tours.started_at <= ?', Time.zone.now)
    .where('tours.finished_at >= ? OR tours.finished_at IS NULL', Time.zone.now)
    .where('tours.reviewed_at >= ? OR tours.reviewed_at IS NULL', Time.zone.now)
  }

  validates :name, :season, presence: true
  validates :name, uniqueness: { scope: :season }, allow_nil: true
  validate :finished_at_greater_than_started_at,
           :reviewed_at_greater_than_finished_at,
           :reviewed_at_greater_than_started_at

  def active?
    started_at.present? && started_at <= Time.zone.now
  end

  def calculate_score_for(user)
    Score
    .joins(solution: [:participation, :problem])
    .where(problems: { tour_id: id },
           participations: { user_id: user.id })
    .sum(:value)
  end

  def finished?
    finished_at.present? && finished_at <= Time.zone.now
  end

  def reviewed?
    reviewed_at.present? && reviewed_at <= Time.zone.now
  end

  def solutionable?
    active? && !finished? && !reviewed?
  end

  private

  def finished_at_greater_than_started_at
    greater_than :finished_at, :started_at
  end

  def reviewed_at_greater_than_finished_at
    greater_than :reviewed_at, :finished_at
  end

  def reviewed_at_greater_than_started_at
    greater_than :reviewed_at, :started_at
  end

  def greater_than(first, second)
    first_value = self[first.to_sym]
    second_value = self[second.to_sym]

    return unless first_value.present? && second_value.present?
    return unless first_value < second_value

    errors.add(first.to_sym,
               I18n.t('validate.greater_than_another_field',
                      field: self.class.human_attribute_name(second)))
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  load_and_authorize_resource except: [:new, :results]
  load_resource only: [:results]

  decorates_assigned :tour

  before_action :prepare_breadcrumbs, only: [:show, :edit, :results]

  helper_method :current_participation

  def show
    @participation = Participation.find_or_initialize_by(user: current_user,
                                                         season: @tour.season)
  end

  def new
    @tour = Tour.new(season_id: params[:season_id])
    authorize! :new, @tour
    prepare_breadcrumbs
  end

  def edit
  end

  def create
    if @tour.save
      redirect_to @tour, notice: t('model.created')
    else
      render :new
    end
  end

  def update
    if @tour.update(tour_params)
      redirect_to @tour, notice: t('model.updated')
    else
      render :edit
    end
  end

  def destroy
    @tour.destroy

    redirect_to root_url, notice: t('model.destroyed')
  rescue StandardError
    redirect_to root_url, alert: t('model.not_destroyed')
  end

  def results
    authorize! :view_results, tour
    @users = User.joins(:participations)
                 .where(role: User.roles[:user])
                 .where(participations: { season: @tour.season })
  end

  private

  def current_participation
    @current_participation ||= current_user_participations.find_by(
      season: @tour.try(:season)
    ) if @tour.present?
  end

  def tour_params
    params
    .require(:tour)
    .permit(:name, :description, :season_id,
            :started_at, :finished_at, :reviewed_at)
  end

  def prepare_breadcrumbs
    add_breadcrumb @tour.season.tournament.name, :root_path
    add_breadcrumb @tour.season.name, :root_path
    add_breadcrumb @tour.name || t('tour.new'), @tour
  end
end

app/views/tours/_form.html.slim
= bootstrap_form_for tour do |f|
  = f.text_field :name
  = f.datetime_select :started_at, include_blank: true
  = f.datetime_select :finished_at, include_blank: true
  = f.datetime_select :reviewed_at, include_blank: true
  = f.text_area :description, data: { provide: 'markdown' }
  = f.hidden_field :season_id
  = f.submit

app/views/tours/_judgement_form.html.slim
.judgement
  - problem.solutions.each do |solution|
    =m solution.content
    = render 'scores/form', score: solution.score_for(current_participation)

app/views/tours/_tour.html.slim
.tour class=(tour.state)
  = link_to tour.name, tour, class: 'name'

  = actions_for tour, class: 'pull-right'

app/views/tours/edit.html.slim
h3
  => t('header.edit')

= render 'form', tour: @tour

app/views/tours/new.html.slim
h3
  => t('header.new')

= render 'form', tour: @tour

app/views/tours/results.html.slim
#tour.results class=(tour.state)
  .jumbotron
    h1
      =t 'tour.results'
    h2
      = tour.name

.panel.panel-default
  .panel-body
    table.table
      thead
        tr
          th
            =t 'result.user'
          th
            =t 'result.score'
      tbody
        - @users.each do |user|
          tr
            td
              = user.name
            td
              = tour.calculate_score_for(user)

app/views/tours/show.html.slim
#tour class=(tour.state)
  .jumbotron
    h1
      = tour.name
      = actions_for tour, class: 'pull-right'

    =m tour.description

    - if tour.reviewed?
      = link_to t('tour.results'), results_tour_path(tour), class: 'btn btn-primary btn-lg'

    - if @participation.new_record? && can?(:create, @participation)
      p
        = render 'participations/form', participation: @participation, label: t('season.participate')

  #problems
    - if can? :create, Problem
      = tour.new_problem

    = render tour.problems